### ISSUE TITLE
Is there any paper of your novel gan-reverser?

### ISSUE THREAD

**Issue by oyxhust** [aleju/gan-reverser#1]
If you have published some papers, please give me an arxiv link. Thanks!

**Comment by aleju** [comment]
See the repository [gan-error-avoidance](https://github.com/aleju/gan-error-avoidance) and paper [1707.00768](https://arxiv.org/abs/1707.00768) for an updated version of the method.

**Comment by oyxhust** [comment]
Thanks a lot. I will go through your paper :).
